<?php if(isset($this->user)  && count($this->user)): ?>

<form id="formulario" action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
    <h3 align="center">EDITAR REGISTRO Nº: <?php echo $this->user['id']?></h3>
    <fieldset>
        <legend>Usuarios</legend>
        <b>ID:</b><input disabled="disabled" type="text" name="id" value="<?php echo $this->user['id']?>">
        <input type="hidden" name="id2" value="<?php echo $this->user['id']?>"><br />
        <b>Dni:</b> <input type="text" name="dni" value="<?php echo $this->user['dni']?>" maxlength="20" size="25"/>
        <b>Nombre:</b> <input type="text" name="nombre" value="<?php echo $this->user['nombre']?>" maxlength="20" size="25"/>
        <b>Apellidos:</b> <input type="text" name="apellidos" value="<?php echo $this->user['apellidos']?>" maxlength="35" size="40"/>
    </fieldset>
</form>

<?php else: ?>

    <p><strong>No hay datos en la base de datos</strong></p>

<?php endif; ?>

<p><a href="<?php echo BASE_URL . 'user' ?>">&lt;&lt; Volver a la lista de usuarios</a></p>