<?php if(isset($this->user)  && count($this->user)): ?>

<form id="formulario" action="<?php echo BASE_URL . 'user/edit/' . $this->user['id']; ?>" method="post">
    <h3 align="center">EDITAR REGISTRO Nº: <?php echo $this->user['id']?></h3>
    <fieldset>
        <legend>Usuario</legend>
        <input type="hidden" name="id" value="<?php echo $this->user['id']?>">
        <b>Dni:</b>
        <input type="text" name="dni" value="<?php echo $this->user['dni']?>" maxlength="20" size="25"/>
        <br />
        <b>Nombre:</b>
        <input type="text" name="nombre" value="<?php echo $this->user['nombre']?>" maxlength="20" size="25"/>
        <br />
        <b>Apellidos:</b>
        <input type="text" name="apellidos" value="<?php echo $this->user['apellidos']?>" maxlength="35" size="40"/>
        <br />
        <input type="submit" name="submit" value="Editar">
    </fieldset>
</form>
<?php else: ?>
    <p>No hay datos en la base de datos</p>
    <p>Por favor, revisa que la id del usuario sea correcta</p>
<?php endif; ?>

<p><a href="<?php echo BASE_URL . 'user' ?>">&lt;&lt; Volver a la lista de usuarios</a></p>