<?php if(isset($this->users)  && count($this->users)): ?>

<table border="1">

    <tr>
        <td>Id</td>
        <td>Dni</td>
        <td>Nombre</td>
        <td>Apellidos</td>
    </tr>

<?php foreach ($this->users as $user): ?>
    <tr>
        <td><?php echo $user['id']?></td>
        <td><?php echo $user['dni']?></td>
        <td><?php echo $user['nombre']?></td>
        <td><?php echo $user['apellidos']?></td>
    </tr>
<?php endforeach; ?>

</table>

<?php else: ?>

    <p><strong>No hay datos en la base de datos</strong></p>

<?php endif; ?>