<?php if(isset($this->user)  && count($this->user)): ?>

<table>
    <tr>
        <th>Id</th>
        <th>Dni</th>
        <th>Nombre</th>
        <th>Apellidos</th>
        <th colspan="2">Operaciones</th>
    </tr>
    <tr id="cuerpo">
        <td><?php echo $this->user['id']?></td>
        <td><?php echo $this->user['dni']?></td>
        <td><?php echo $this->user['nombre']?></td>
        <td><?php echo $this->user['apellidos']?></td>
        <td>
            <a href="<?php echo BASE_URL . 'user/edit/' . $this->user['id']; ?>">Editar</a>
        </td>
        <td>
            <a href="<?php echo BASE_URL . 'user/delete/' . $this->user['id']; ?>">Eliminar</a>
        </td>
    </tr>

</table>
<?php else: ?>
    <p><strong>No hay datos en la base de datos</strong></p>
<?php endif; ?>

<p><a href="<?php echo BASE_URL . 'user' ?>">&lt;&lt; Volver a la lista de usuarios</a></p>
