<?php if(isset($this->orders)  && count($this->orders)): ?>

<table>
    <tr>
        <th>Referencia</th>
        <th colspan="3">Operaciones</th>
    </tr>
<?php foreach ($this->orders as $order): ?>
    <tr id="cuerpo">
        <td><?php echo $order['referencia']?></td>

        <td>
            <a href="<?php echo BASE_URL . 'order/view/' . $order['id']; ?>">Ver</a>
        </td>
        <td>
            <a href="<?php echo BASE_URL . 'order/addproduct/' . $order['id']; ?>">Añadir producto</a>
        </td>
        <td>
            <a href="<?php echo BASE_URL . 'order/delete/' . $order['id']; ?>">Eliminar</a>
        </td>
    </tr>
<?php endforeach; ?>
    <tr>
        <td colspan="7"><a href="<?php echo BASE_URL . 'order/add' ?>">Añadir nuevo pedido</a></td>
    </tr>
</table>

<?php else: ?>
    <p><strong>No hay datos en la base de datos</strong></p>
<?php endif; ?>