<?php if(isset($this->order)  && count($this->order)): ?>
<table>
    <tr>
        <th>
            <a href="<?php echo BASE_URL ?>user/view/<?php echo $this->order[0]['usuario_id'] ?>">Cliente: <?php  echo $this->order[0]['usuario']?></a></th>
        <th>Referencia: <?php echo $this->order[0]['referencia'] ?></th>
        <td>
            <a href="<?php echo BASE_URL . 'order/edit/' . $this->order[0]['id']; ?>">Editar</a>
        </td>
        <td>
            <a href="<?php echo BASE_URL . 'order/delete/' . $this->order[0]['id']; ?>">Eliminar</a>
        </td>
    </tr>
    <tr>&nbsp;</tr>
    <tr>&nbsp;</tr>
    <tr>&nbsp;</tr>
    <tr>
        <th>Producto</th>
        <th>Cantidad</th>
        <th>Precio Unidad</th>
        <th>Precio Total</th>
    </tr>
    <?php
        $total = 0;
        foreach ($this->order as $order):
    ?>
    <tr id="cuerpo">
        <?php $total += $order['precio_total'];?>
        <td><?php echo $order['nombre']?></td>  
        <td><?php echo $order['cantidad']?></td>  
        <td><?php echo $order['precio']?></td>  
        <td><?php echo $order['precio_total']?></td>  
    </tr>

<?php endforeach; ?>
    <tr>
        <td colspan="2">&nbsp;</td>
        <th>TOTAL</th>
        <td><?php echo $total ?></td>
    </tr>
</table>
<?php else: ?>
    <p><strong>No hay datos en la base de datos</strong></p>
<?php endif; ?>

<p><a href="<?php echo BASE_URL . 'order' ?>">&lt;&lt; Volver a la lista de usuarios</a></p>
